### ISSUE TITLE
What if user doesn't use iCloud?

### ISSUE THREAD

**Issue by rmvz3** [fabiocaccamo/FCUUID#4]
Hi, I find your library is perfect to accomplish my client's app requirements and identify users. I'd need to use the uuidForDevice method to identify the user device. However I have a few questions:

-As I understand your library, it relies in NSUbiquitousKeyValueStore to persist across installations but, what happens if the user is logged out or even never created a iCloud account? This app is meant to be used mostly by old people so this can be an usual scenario. If this is the case, there's nothing to do, Am I right? Or there is any kind of automatically generated iCloud id created on iPhone activation?

-Can you identify just the current device instead of every user devices?

Thank you very much

Ricardo Mantero

**Comment by fabiocaccamo** [comment]
Hi Ricardo, 
the **only one** method which depends on `NSUbiquitousKeyValueStore` *(then iCloud)* is `uuidsOfUserDevices`.

`uuidsOfUserDevices` uses iCloud because it's the only way to share data of the same user across his devices without any login.

If iCloud is not available or disabled `uuidsOfUserDevices` returns only the uuid of the current device.

**Comment by rmvz3** [comment]
Ok. Fabio, thank you for answering so quickly.

Then I could identify an **unique** device even after a restore **without** heve been signed in iCloud?

That would be just too good to be true :D

**Comment by fabiocaccamo** [comment]
If you just need to identify a device you should use `uuidForDevice`.

**Comment by rmvz3** [comment]
Thank you, Fabio.
